package client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * DemoService service = new DemoService();
 * DemoDelegate portType = service.getDemoPort();
 * portType.sayHello(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "DemoService", targetNamespace = "http://server/", wsdlLocation = "http://127.0.0.1:8080/WebServicesTest/DemoPort?wsdl")
public class DemoService extends Service {

	private final static URL DEMOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(client.DemoService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = client.DemoService.class.getResource(".");
			url = new URL(baseUrl,
					"http://127.0.0.1:8080/WebServicesTest/DemoPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/WebServicesTest/DemoPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		DEMOSERVICE_WSDL_LOCATION = url;
	}

	public DemoService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DemoService() {
		super(DEMOSERVICE_WSDL_LOCATION, new QName("http://server/",
				"DemoService"));
	}

	/**
	 * 
	 * @return returns DemoDelegate
	 */
	@WebEndpoint(name = "DemoPort")
	public DemoDelegate getDemoPort() {
		return super.getPort(new QName("http://server/", "DemoPort"),
				DemoDelegate.class);
	}

}
