package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "FileTransDelegate", targetNamespace = "http://server/")
public interface FileTransDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sayHello", targetNamespace = "http://server/", className = "client.SayHello")
	@ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://server/", className = "client.SayHelloResponse")
	public String sayHello(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
