package client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * FileTransService service = new FileTransService();
 * FileTransDelegate portType = service.getFileTransPort();
 * portType.sayHello(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "FileTransService", targetNamespace = "http://server/", wsdlLocation = "http://127.0.0.1:8080/WebServicesTest/FileTransPort?wsdl")
public class FileTransService extends Service {

	private final static URL FILETRANSSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(client.FileTransService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = client.FileTransService.class.getResource(".");
			url = new URL(baseUrl,
					"http://127.0.0.1:8080/WebServicesTest/FileTransPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/WebServicesTest/FileTransPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		FILETRANSSERVICE_WSDL_LOCATION = url;
	}

	public FileTransService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public FileTransService() {
		super(FILETRANSSERVICE_WSDL_LOCATION, new QName("http://server/",
				"FileTransService"));
	}

	/**
	 * 
	 * @return returns FileTransDelegate
	 */
	@WebEndpoint(name = "FileTransPort")
	public FileTransDelegate getFileTransPort() {
		return super.getPort(new QName("http://server/", "FileTransPort"),
				FileTransDelegate.class);
	}

}
